### ISSUE TITLE
升级了什么啊？怎么更新报错了啊！~~

### ISSUE THREAD

**Issue by indiboy** [hulang/think-addons#2]
> @php think service:discover

Fatal error: Uncaught ReflectionException: Class "app" does not exist in D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php:377
Stack trace:
#0 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(377): ReflectionClass->__construct('app')
#1 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(253): think\Container->invokeClass('app', Array)
#2 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(47): think\Container->make('app', Array, false)
#3 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(97): think\Facade::createFacade()
#4 D:\MyCode\mp.domian.cn\vendor\hulang\think-addons\src\helper.php(13): think\Facade::__callStatic('getRootPath', Array)
#5 [internal function]: {closure}('app')
#6 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(377): ReflectionClass->__construct('app')
#7 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(253): think\Container->invokeClass('app', Array)
#8 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(47): think\Container->make('app', Array, false)
#9 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(97): think\Facade::createFacade()
#10 D:\MyCode\mp.domian.cn\vendor\hulang\think-addons\src\helper.php(13): think\Facade::__callStatic('getRootPath', Array)
#11 [internal function]: {closure}('Illuminate\\Supp...')
#12 D:\MyCode\mp.domian.cn\vendor\jaeger\querylist\src\Collect\Support\helpers.php(8): class_exists('Illuminate\\Supp...')
#13 D:\MyCode\mp.domian.cn\vendor\composer\autoload_real.php(41): require('D:\\MyCode\\mp.ch...')
#14 D:\MyCode\mp.domian.cn\vendor\composer\autoload_real.php(45): {closure}('0f675193b08f1d9...', 'D:\\MyCode\\mp.ch...')
#15 D:\MyCode\mp.domian.cn\vendor\autoload.php(25): ComposerAutoloaderInit8a36b22e1b1598149c18bfb99b379158::getLoader()
#16 D:\MyCode\mp.domian.cn\think(7): require('D:\\MyCode\\mp.ch...')
#17 {main}

Next think\exception\ClassNotFoundException: class not exists: app in D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php:379
Stack trace:
#0 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(253): think\Container->invokeClass('app', Array)
#1 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(47): think\Container->make('app', Array, false)
#2 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(97): think\Facade::createFacade()
#3 D:\MyCode\mp.domian.cn\vendor\hulang\think-addons\src\helper.php(13): think\Facade::__callStatic('getRootPath', Array)
#4 [internal function]: {closure}('app')
#5 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(377): ReflectionClass->__construct('app')
#6 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(253): think\Container->invokeClass('app', Array)
#7 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(47): think\Container->make('app', Array, false)
#8 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(97): think\Facade::createFacade()
#9 D:\MyCode\mp.domian.cn\vendor\hulang\think-addons\src\helper.php(13): think\Facade::__callStatic('getRootPath', Array)
#10 [internal function]: {closure}('Illuminate\\Supp...')
#11 D:\MyCode\mp.domian.cn\vendor\jaeger\querylist\src\Collect\Support\helpers.php(8): class_exists('Illuminate\\Supp...')
#12 D:\MyCode\mp.domian.cn\vendor\composer\autoload_real.php(41): require('D:\\MyCode\\mp.ch...')
#13 D:\MyCode\mp.domian.cn\vendor\composer\autoload_real.php(45): {closure}('0f675193b08f1d9...', 'D:\\MyCode\\mp.ch...')
#14 D:\MyCode\mp.domian.cn\vendor\autoload.php(25): ComposerAutoloaderInit8a36b22e1b1598149c18bfb99b379158::getLoader()
#15 D:\MyCode\mp.domian.cn\think(7): require('D:\\MyCode\\mp.ch...')
#16 {main}
  thrown in D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php on line 379
PHP Fatal error:  Uncaught ReflectionException: Class "app" does not exist in D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php:377
Stack trace:
#0 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(377): ReflectionClass->__construct('app')
#1 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(253): think\Container->invokeClass('app', Array)
#2 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(47): think\Container->make('app', Array, false)
#3 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(97): think\Facade::createFacade()
#4 D:\MyCode\mp.domian.cn\vendor\hulang\think-addons\src\helper.php(13): think\Facade::__callStatic('getRootPath', Array)
#5 [internal function]: {closure}('app')
#6 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(377): ReflectionClass->__construct('app')
#7 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(253): think\Container->invokeClass('app', Array)
#8 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(47): think\Container->make('app', Array, false)
#9 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(97): think\Facade::createFacade()
#10 D:\MyCode\mp.domian.cn\vendor\hulang\think-addons\src\helper.php(13): think\Facade::__callStatic('getRootPath', Array)
#11 [internal function]: {closure}('Illuminate\\Supp...')
#12 D:\MyCode\mp.domian.cn\vendor\jaeger\querylist\src\Collect\Support\helpers.php(8): class_exists('Illuminate\\Supp...')
#13 D:\MyCode\mp.domian.cn\vendor\composer\autoload_real.php(41): require('D:\\MyCode\\mp.ch...')
#14 D:\MyCode\mp.domian.cn\vendor\composer\autoload_real.php(45): {closure}('0f675193b08f1d9...', 'D:\\MyCode\\mp.ch...')
#15 D:\MyCode\mp.domian.cn\vendor\autoload.php(25): ComposerAutoloaderInit8a36b22e1b1598149c18bfb99b379158::getLoader()
#16 D:\MyCode\mp.domian.cn\think(7): require('D:\\MyCode\\mp.ch...')
#17 {main}

Next think\exception\ClassNotFoundException: class not exists: app in D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php:379
Stack trace:
#0 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(253): think\Container->invokeClass('app', Array)
#1 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(47): think\Container->make('app', Array, false)
#2 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(97): think\Facade::createFacade()
#3 D:\MyCode\mp.domian.cn\vendor\hulang\think-addons\src\helper.php(13): think\Facade::__callStatic('getRootPath', Array)
#4 [internal function]: {closure}('app')
#5 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(377): ReflectionClass->__construct('app')
#6 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php(253): think\Container->invokeClass('app', Array)
#7 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(47): think\Container->make('app', Array, false)
#8 D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Facade.php(97): think\Facade::createFacade()
#9 D:\MyCode\mp.domian.cn\vendor\hulang\think-addons\src\helper.php(13): think\Facade::__callStatic('getRootPath', Array)
#10 [internal function]: {closure}('Illuminate\\Supp...')
#11 D:\MyCode\mp.domian.cn\vendor\jaeger\querylist\src\Collect\Support\helpers.php(8): class_exists('Illuminate\\Supp...')
#12 D:\MyCode\mp.domian.cn\vendor\composer\autoload_real.php(41): require('D:\\MyCode\\mp.ch...')
#13 D:\MyCode\mp.domian.cn\vendor\composer\autoload_real.php(45): {closure}('0f675193b08f1d9...', 'D:\\MyCode\\mp.ch...')
#14 D:\MyCode\mp.domian.cn\vendor\autoload.php(25): ComposerAutoloaderInit8a36b22e1b1598149c18bfb99b379158::getLoader()
#15 D:\MyCode\mp.domian.cn\think(7): require('D:\\MyCode\\mp.ch...')
#16 {main}
  thrown in D:\MyCode\mp.domian.cn\vendor\topthink\framework\src\think\Container.php on line 379
Script @php think service:discover handling the post-autoload-dump event returned with error code 255

**Comment by hulang** [comment]
根目录下的：`composer.json`中
```
    "config": {
        "preferred-install": "dist",
        "optimize-autoloader": true
    },
```

`"optimize-autoloader": true`增加这个试试

**Comment by hulang** [comment]
另外，这不是我插件错误。是tp的错误，我之前也提示这个错误
我问了`workerman`的作者，它说这就是tp的错误。
https://www.workerman.net/q/12818

**Comment by indiboy** [comment]
是在执行 /php think service:discover 时候报错的，卸载了就好了。
不知道怎么看日志，php版本是8.1，搜了下很多人说是php版本的问题。
Script php think service:discover handling the post-autoload-dump event returned with error code 255

**Comment by indiboy** [comment]
没有你这个插件，正常，安装了就报错，应该是你这个插件哪里兼容性有问题。

**Comment by hulang** [comment]
@indiboy 你按照我发的进行操作了吗？`"optimize-autoloader": true`

**Comment by hulang** [comment]
![124](https://github.com/user-attachments/assets/f25c36fa-94c8-4281-816e-9f674593ff95)
@indiboy 你设置一下跟目下(也就是项目目录下)`composer.json`
`config`项
```
    "config": {
        "optimize-autoloader": true
    },
```
改成
```
    "config": {
        "preferred-install": "dist",
        "optimize-autoloader": true
    },
```

**Comment by hulang** [comment]
设置后，重新安装试试

**Comment by hulang** [comment]
@indiboy 可以正常安装了吗？可以的话，我关闭`issues`了

**Comment by indiboy** [comment]
> @indiboy 可以正常安装了吗？可以的话，我关闭`issues`了

没有任何作用，报错是一样的。但是我新安装一个tp，同样环境，只安装你这一个扩展时没有问题了，没有报错。

**Comment by indiboy** [comment]
> @indiboy 可以正常安装了吗？可以的话，我关闭`issues`了

特意一个一个实验了一下 ，你的和这个 jaeger/querylist 冲突？
你实验一下，单独安装每一个都没问题，一起安装就报错了。

**Comment by hulang** [comment]
@indiboy 今天到公司了，我到我的项目中进行了安装：`composer require jaeger/querylist`
是没有问题的。下面的`GIF`图片有点大
![安装](https://github.com/user-attachments/assets/0d6526ce-1f7f-4a18-bc8d-de2dc0eb439e)

**Comment by hulang** [comment]
我发现安装`jaeger/querylist`在我的项目中的版本是`(V3.2.1)`，但是我在`packagist.org`上看到的最新版本是：`V4.4.5`
我强制改为`^V4.0.0`，提示很多插件错误，一大堆错误。。
是不是你要安装`jaeger/querylist ^V4.0.0`的原因？

**Comment by indiboy** [comment]
> 我发现安装`jaeger/querylist`在我的项目中的版本是`(V3.2.1)`，但是我在`packagist.org`上看到的最新版本是：`V4.4.5` 我强制改为`^V4.0.0`，提示很多插件错误，一大堆错误。。 是不是你要安装`jaeger/querylist ^V4.0.0`的原因？

是的，安装的 4.0 以上版本，应该时4.4.5，单独安装谁都没问题，和一起就报错了。

**Comment by hulang** [comment]
@indiboy 升级下我的插件试试，我这边可以了。。

**Comment by hulang** [comment]
@indiboy 你好，你那边可以安装v4了吗？我这边可以了，看到回复一下，我好`关闭`issues

**Comment by indiboy** [comment]
不知道为什么，我这里搜不到 3.0.13 的包
只有3.0.4的。

**Comment by hulang** [comment]
@indiboy 使用命令
```sh
composer update -vvv
```
试试
